baseURL = 'https://.schalappe.page/'
languageCode = 'fr-fr'
title = 'Abdallah Hakim Kone'
theme = "alexa"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Photos'
    url = 'https://photos.schalappe.page/'
    weight = 50
    [menus.main.params]
    rel = 'external'

[params]
  [params.contact]
    email = 'konehakim@gmail.com'
    phone = '+33 6 67 63 93 99'
