baseURL = 'https://.schalappe.page/'
languageCode = 'fr-fr'
title = 'Abdallah Hakim Kone'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
    [menus.main.params]
      class = 'fa-solid fa-house'

  [[menus.main]]
    name = 'Photos'
    url = 'https://photos.schalappe.page/'
    weight = 50
    rel = 'external'
    [menus.main.params]
      class = 'fa-solid fa-camera'

[params]
  [params.contact]
    email = 'konehakim@gmail.com'
    phone = '+33 6 67 63 93 99'

[module]
  [module.hugoVersion]
    extended = false
    smin = "0.116.0"
