baseURL = "https://.schalappe.page/"
theme = "PaperMod"
languageCode = "fr-fr"
title = "Abdallah Hakim Kone"

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
    [menus.main.params]
      class = "fa-solid fa-house"

  [[menus.main]]
    name = "Blog"
    url = "/blog"
    weight = 20
    [menus.main.params]
      class = "fa-solid fa-blog"
  
  [[menus.main]]
    name = "Archives"
    url = "/blog/archives/"
    weight = 30
    [menus.main.params]
      class = "fa-solid fa-clock"

  [[menus.main]]
    name = "Tags"
    url = "/blog/tags/"
    weight = 40
    [menus.main.params]
      class = "fa-solid fa-tag"

  [[menus.main]]
    name = "Photos"
    url = "https://photos.schalappe.page/"
    weight = 50
    rel = "external"
    [menus.main.params]
      class = "fa-solid fa-camera"

[params]
  [params.contact]
    email = "konehakim@gmail.com"
    phone = "+33 6 67 63 93 99"

[params.PaperMod]
  # Future PaperMod specific configurations can be added here. Examples:
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  defaultTheme = "auto" # auto, light, dark
  disableThemeToggle = false

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
